# Configuration for https://goreleaser.com/
project_name: kubectl-mc

builds:
  - goos:
      - darwin
      - linux
      - windows

release:
  github:
    owner: jonnylangefeld
    name: kubectl-mc
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
