apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mc
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jonnylangefeld/kubectl-mc
  shortDescription: Run kubectl commands against multiple clusters at once
  description: |+2
    `kubectl mc` (short for multi cluster) executes commands against multiple 
    clusters in your context in parallel. The clusters are selected by a 
    regular expression.

    For example you can list the pods in the kube-system namespace of all development clusters
    with the following command:
    mc -r development -- get pods -n kube-system

    For more examples run kubectl mc --help
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-mc
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-mc
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-mc.exe
